### PR TITLE
Migrate from .NET Core 3.1 to .NET 5

### PR DESCRIPTION
**Pull request by zkhussain**
This builds successfully without any issues as far as I am seeing except with one warning:
image
From what I read, it is ambiguous as to what is the first record for that expression, and we have to somehow filter it like it's saying.

### CODE REVIEW

**Comment by jasekiw** [comment]
@zkhussain we are going to need to find a way to not add the underscore for every property name, that will break the frontend. As things are not expecting an underscore.

**Comment by zkhussain** [comment]
> @zkhussain we are going to need to find a way to not add the underscore for every property name, that will break the frontend. As things are not expecting an underscore.

Was thinking about that. Without the underscore, it is not able to recognize the properties. Could we edit the database to remove the underscore?

**Comment by jasekiw** [comment]
> > @zkhussain we are going to need to find a way to not add the underscore for every property name, that will break the frontend. As things are not expecting an underscore.
> 
> Was thinking about that. Without the underscore, it is not able to recognize the properties. Could we edit the database to remove the underscore?

@zkhussain 

"EFCore.Naming Conventions" handles this automatically. You need to consult that package. You updated it, check the documentation.

**Comment by zkhussain** [comment]
> 
> 
> > > @zkhussain we are going to need to find a way to not add the underscore for every property name, that will break the frontend. As things are not expecting an underscore.
> > 
> > 
> > Was thinking about that. Without the underscore, it is not able to recognize the properties. Could we edit the database to remove the underscore?
> 
> @zkhussain
> 
> "EFCore.Naming Conventions" handles this automatically. You need to consult that package. You updated it, check the documentation.

It's fixed now, thanks @jasekiw.

**Review by jasekiw — APPROVED** [review]
Waiting for all other PR's to be merged before merging this.

**Comment by jasekiw** [comment]
closing in favor of .net 6 pr.

**Pull request closed without merging**
